index:
    pattern:  /
    defaults: { _controller: TabooMainBundle:Main:index }

composerBase:
    pattern: /composer
    defaults: { _controller: TabooMainBundle:Composer:base }
    
sandbox:
    pattern: /sandbox
    defaults: { _controller: TabooMainBundle:Main:sandbox }